---
- hosts: localhost
  vars:
    packages:
      brew:
        - name: mas
        - name: terraform
        - name: tfsec
      cask:
        - name: eset-cyber-security-pro
        - name: google-chrome
        - name: iterm2
        - name: pycharm-ce
        - name: rancher
        - name: veracrypt
      mas:
        - 425424353  # The Unarchiver
        - 467622356  # Abby Lingvo
        - 497799835  # XCode
        - 803453959  # Slack
        - 930093508  # Shapes
    packages_exclude:
      brew: []
      cask: []
      mas: []
    osx_defaults:
    - key: AppleMeasurementUnits
      type: string
      value: Centimeters
    - key: AppleLanguages
      type: array
      value:
        - "en-US"
        - "cs-CZ"
        - "fr-BE"
        - "nl-NL"
        - "ru-RU"
    - domain: com.apple.Safari
      key: IncludeInternalDebugMenu
      type: bool
      value: true
    - domain: com.apple.desktopservices
      key: DSDontWriteNetworkStores
      type: bool
      value: true
    - domain: com.apple.dock
      key: autohide
      type: bool
      value: true
    - domain: com.apple.dock
      key: largesize
      type: float
      value: 57
    - domain: com.apple.dock
      key: magnification
      type: bool
      value: true
    - domain: com.apple.dock
      key: tilesize
      type: float
      value: 33
    - domain: com.apple.finder
      key: FXDefaultSearchScope
      type: string
      value: SCcf
    - domain: com.apple.finder
      key: FXEnableExtensionChangeWarning
      type: bool
      value: false
    - domain: com.apple.finder
      key: FXPreferredViewStyle
      type: string
      value: Nlsv
    - domain: com.apple.finder
      key: QuitMenuItem
      type: bool
      value: true
    - domain: com.apple.finder
      key: ShowPathbar
      type: bool
      value: true
    - domain: com.apple.screencapture
      key: location
      type: string
      value: /Users/bernardn/Pictures/screenshots
  roles:
  - role: brew
  - role: defaults
  - role: dotfiles
