---

- name: Git Repo
  ansible.builtin.git:
    repo: 'git@github.com:bernardn/dotfiles.git'
    dest: "{{ ansible_env.HOME }}/.dotfiles/"
    single_branch: yes
    version: master

- name: Source .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: '. ~/.dotfiles/.bashrc'
    insertbefore: BOF
